spring:
  config:
    import: optional:consul:127.0.0.1:8500
  application:
    name: iot-iam
  cloud:
    consul:
      scheme: http
      host: ${CONSUL_SERVER_HOST:127.0.0.1}
      port: ${CONSUL_SERVER_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}
        health-check-path: /iot/iam/actuator/health
        prefer-agent-address: true
        hostname: ${spring.application.name}
        catalog-services-watch-timeout: 5
        health-check-timeout: 15s
        deregister: true
        heartbeat:
          enabled: true
        health-check-critical-timeout: 10s
      config:
        enabled: true
        format: YAML
        name: app
        data-key: config
        profileSeparator: "::"
        prefixes: dev
        watch:
          enabled: true
